object fListJualObat: TfListJualObat
  Left = 192
  Top = 125
  AutoScroll = False
  BorderIcons = []
  Caption = 'fListJualObat'
  ClientHeight = 636
  ClientWidth = 1289
  Color = clGradientInactiveCaption
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poDesktopCenter
  PixelsPerInch = 96
  TextHeight = 13
end
